export interface Option<T> {
  value: T;
  label: string;
}
export enum UF {
  AC = "AC",
  AL = "AL",
  AP = "AP",
  AM = "AM",
  BA = "BA",
  CE = "CE",
  DF = "DF",
  ES = "ES",
  GO = "GO",
  MA = "MA",
  MT = "MT",
  MS = "MS",
  MG = "MG",
  PA = "PA",
  PB = "PB",
  PR = "PR",
  PE = "PE",
  PI = "PI",
  RJ = "RJ",
  RN = "RN",
  RS = "RS",
  RO = "RO",
  RR = "RR",
  SC = "SC",
  SP = "SP",
  SE = "SE",
  TO = "TO",
}

export const UF_LIST_OPTIONS: Option<UF>[] = [
  { label: "AC", value: UF.AC },
  { label: "AL", value: UF.AL },
  { label: "AP", value: UF.AP },
  { label: "AM", value: UF.AM },
  { label: "BA", value: UF.BA },
  { label: "CE", value: UF.CE },
  { label: "DF", value: UF.DF },
  { label: "ES", value: UF.ES },
  { label: "GO", value: UF.GO },
  { label: "MA", value: UF.MA },
  { label: "MT", value: UF.MT },
  { label: "MS", value: UF.MS },
  { label: "MG", value: UF.MG },
  { label: "PA", value: UF.PA },
  { label: "PB", value: UF.PB },
  { label: "PR", value: UF.PR },
  { label: "PE", value: UF.PE },
  { label: "PI", value: UF.PI },
  { label: "RJ", value: UF.RJ },
  { label: "RN", value: UF.RN },
  { label: "RS", value: UF.RS },
  { label: "RO", value: UF.RO },
  { label: "RR", value: UF.RR },
  { label: "SC", value: UF.SC },
  { label: "SP", value: UF.SP },
  { label: "SE", value: UF.SE },
  { label: "TO", value: UF.TO },
];

export const UF_LIST = [
  UF.AC,
  UF.AL,
  UF.AP,
  UF.AM,
  UF.BA,
  UF.CE,
  UF.DF,
  UF.ES,
  UF.GO,
  UF.MA,
  UF.MT,
  UF.MS,
  UF.MG,
  UF.PA,
  UF.PB,
  UF.PR,
  UF.PE,
  UF.PI,
  UF.RJ,
  UF.RN,
  UF.RS,
  UF.RO,
  UF.RR,
  UF.SC,
  UF.SP,
  UF.SE,
  UF.TO,
] as const;
